spring:
  application:
    name: demo
  ai:
    bedrock:
      aws:
        region: us-east-1
        # access-key: ${AWS_ACCESS_KEY_ID} # 환경 변수나 ~/.aws/credentials 사용 권장
        # secret-key: ${AWS_SECRET_ACCESS_KEY}
      converse:
        chat:
          enabled: true
          options:
            model: us.amazon.nova-lite-v1:0

logging:
  level:
    root: debug
    com.example: debug
